import { Field, NumberKeyboard, DatetimePicker, Button, Icon, Tabbar, TabbarItem, Cell, Checkbox, Toast, PullRefresh, List, CellGroup, Popup } from 'vant'
import Vue from 'vue'
Vue.use(Button)
Vue.use(Icon)
Vue.use(Tabbar)
Vue.use(TabbarItem)
Vue.use(Cell)
Vue.use(Checkbox)
Vue.use(Toast)
Vue.use(PullRefresh)
Vue.use(List)
Vue.use(CellGroup)
Vue.use(Popup)
Vue.use(DatetimePicker)
Vue.use(NumberKeyboard)
Vue.use(Field)
